### ISSUE TITLE
Action runs for 30 mins then cancels, no errors

### ISSUE THREAD

**Issue by e10jon** [pullpreview/action#50]
We've been using the action for a while and it's been really great. But recently we encountered a license error, so I bought a license and am providing it to the action. Unfortunately, the action is still failing, even though it appears our app code is working as expected. Can you help?

[run.txt](https://github.com/pullpreview/action/files/12018421/run.txt)

**Comment by crohr** [comment]
Hi @e10jon, and thanks for buying the license. I can confirm the action went through, but as you say something is not working properly when booting the app since it ends up in timeout.

A few things you can try to debug further:
- remove the pullpreview label, wait until the environment is destroyed, then re-apply the label. This will make sure you start from a fresh instance.
- increase the timeout to e.g. 40min just to see if it makes any difference.
- log into the EC2 instance while the deployment is occurring, and have a look around with `htop`, `docker logs`, `docker ps` etc. see if you are running out of memory or see misbehaving containers.
- log into the EC2 instance, and manually start the compose stack to see if any errors are output interactively:

```
ssh ec2-user@IP
cd /app
cat $(env /etc/pullpreview/env) docker-compose -f docker-compose.yml,docker-compose.preview.yml up
```

Judging by the number of containers you start, you may also want to try a larger instance type to see if it makes any difference.

Please let me know if you need any further help, we can also schedule a pairing session if the problem persists.

**Comment by makeitraina** [comment]
Also facing this issue. I will try the steps you mentioned for debugging further.

@e10jon were you able to fix your issues?

**Comment by e10jon** [comment]
Sorry, I forgot to respond on this!

The problem was with our code. I was able to use `docker compose -f docker-compose.yml -f docker-compose.preview.yml up` to identity and fix the problem.
