### ISSUE TITLE
Adding License to `pullpreview.yml` not Working

### ISSUE THREAD

**Issue by leightjohnson93** [pullpreview/action#57]
We have recently purchased a license and adding it to the yaml is not working.
```
license: ${{ secrets.PULLPREVIEW_LICENSE }}
```

I'm not sure how this is supposed to work, since it looks like the action reaches out to an endpoint for license verification.

**Comment by crohr** [comment]
@leightjohnson93 sorry for the confusion: for now the license enablement is manual on my side, and as such since I'm in a different timezone it took some time for me to enable your subscription. It is now done, sorry for the delay. I will work on adding an option to manually input the license token as well.

Thanks again for purchasing the license!

**Comment by geoffatsource** [comment]
We are having the same issue
